name: "ROS1 Ubuntu 18.04"

on:
  push:
    branches: [ master, dockerfile ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
      - name: Create Workspace
        run: |
          export REPO=$(basename $GITHUB_REPOSITORY) &&
          cd $GITHUB_WORKSPACE/.. && mkdir src/ &&
          mv $REPO/ src/ && mkdir $REPO/ && mv src/ $REPO/ && cd $REPO/
      - name: Build Docker
        run: |
          export REPO=$(basename $GITHUB_REPOSITORY) &&
          docker build -t kalibr -f $GITHUB_WORKSPACE/src/$REPO/Dockerfile_ros1_18_04 .

